version: '3'
services:  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - 295devops-travel-lamp-mariadb-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/devopstravel.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - 295devops-travel-lamp-net
  php:
    build: .
    container_name: php
    ports:
      - "8010:80"
    depends_on:
      - mariadb
    networks:
      - 295devops-travel-lamp-net
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8011:80"
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    networks:
      - 295devops-travel-lamp-net
volumes:
  295devops-travel-lamp-mariadb-data: {}
networks:
  295devops-travel-lamp-net:
    external: false